---
apiVersion: v1
kind: Namespace
metadata:
  name: '${ namespace }'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: '${ namespace }'
data:
  NEW_FEATURE: "false"


---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: '${ namespace }'
  labels:
    source: demo
    stack: frontend
    app: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker
    spec:
      containers:
      - name: primary
        image: index.docker.io/nkuleshov/spin-kub-v2-demo
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config

---


kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: '${ namespace }'
spec:
  selector:
    source: demo
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: test1
    
  - protocol: TCP
    port: 90
    targetPort: 9000
    name: test2
